"""Static NSE sector classification for the configured equity universe.

Sector membership is stable public reference data (which NIFTY sectoral index a
company belongs to), not something computed or fabricated -- the same category of
fact as the Dhan security-ID mapping in universe/nse.py. Symbols not present here
fall back to "UNCLASSIFIED" wherever this is consulted, matching the existing
sector-concentration fallback in orchestration/decision_pipeline.py, rather than
guessing a sector for a name this table doesn't cover.
"""

from __future__ import annotations

SECTOR_BY_SYMBOL: dict[str, str] = {
    "AUBANK": "BANKING", "AXISBANK": "BANKING", "BANDHANBNK": "BANKING",
    "BANKBARODA": "BANKING", "BANKINDIA": "BANKING", "CANBK": "BANKING",
    "CUB": "BANKING", "FEDERALBNK": "BANKING", "HDFCBANK": "BANKING",
    "ICICIBANK": "BANKING", "IDFCFIRSTB": "BANKING", "INDIANB": "BANKING",
    "IOB": "BANKING", "KARURVYSYA": "BANKING", "KOTAKBANK": "BANKING",
    "MAHABANK": "BANKING", "PNB": "BANKING", "SBIN": "BANKING",
    "UCOBANK": "BANKING", "UNIONBANK": "BANKING",

    "AADHARHFC": "FINANCIAL_SERVICES", "AAVAS": "FINANCIAL_SERVICES",
    "ABCAPITAL": "FINANCIAL_SERVICES", "BAJAJFINSV": "FINANCIAL_SERVICES",
    "BAJAJHFL": "FINANCIAL_SERVICES", "BAJFINANCE": "FINANCIAL_SERVICES",
    "BSE": "FINANCIAL_SERVICES", "CAMS": "FINANCIAL_SERVICES",
    "CANFINHOME": "FINANCIAL_SERVICES", "CDSL": "FINANCIAL_SERVICES",
    "CHOLAFIN": "FINANCIAL_SERVICES", "GICRE": "FINANCIAL_SERVICES",
    "GODIGIT": "FINANCIAL_SERVICES", "HDBFS": "FINANCIAL_SERVICES",
    "HDFCAMC": "FINANCIAL_SERVICES", "HDFCLIFE": "FINANCIAL_SERVICES",
    "HOMEFIRST": "FINANCIAL_SERVICES", "HUDCO": "FINANCIAL_SERVICES",
    "ICICIAMC": "FINANCIAL_SERVICES", "ICICIGI": "FINANCIAL_SERVICES",
    "ICICIPRULI": "FINANCIAL_SERVICES", "INDIASHLTR": "FINANCIAL_SERVICES",
    "IRFC": "FINANCIAL_SERVICES", "JIOFIN": "FINANCIAL_SERVICES",
    "LICHSGFIN": "FINANCIAL_SERVICES", "LICI": "FINANCIAL_SERVICES",
    "M&MFIN": "FINANCIAL_SERVICES", "MANAPPURAM": "FINANCIAL_SERVICES",
    "MFSL": "FINANCIAL_SERVICES", "MOTILALOFS": "FINANCIAL_SERVICES",
    "MUTHOOTFIN": "FINANCIAL_SERVICES", "NIACL": "FINANCIAL_SERVICES",
    "PFC": "FINANCIAL_SERVICES", "PNBHOUSING": "FINANCIAL_SERVICES",
    "POONAWALLA": "FINANCIAL_SERVICES", "RECLTD": "FINANCIAL_SERVICES",
    "REPCOHOME": "FINANCIAL_SERVICES", "SBILIFE": "FINANCIAL_SERVICES",
    "SHRIRAMFIN": "FINANCIAL_SERVICES", "STARHEALTH": "FINANCIAL_SERVICES",
    "SUNDARMFIN": "FINANCIAL_SERVICES", "TATACAP": "FINANCIAL_SERVICES",
    "APTUS": "FINANCIAL_SERVICES",

    "COFORGE": "IT", "HCLTECH": "IT", "INFOBEAN": "IT", "INFY": "IT",
    "KELLTONTEC": "IT", "KPITTECH": "IT", "LTM": "IT", "LTTS": "IT",
    "MOSCHIP": "IT", "NEWGEN": "IT", "NUCLEUS": "IT", "OFSS": "IT",
    "PERSISTENT": "IT", "TATAELXSI": "IT", "TCS": "IT", "TECHM": "IT",
    "WIPRO": "IT", "BHARTIHEXA": "IT",

    "AUROPHARMA": "PHARMA", "CIPLA": "PHARMA", "DIVISLAB": "PHARMA",
    "DRREDDY": "PHARMA", "GLENMARK": "PHARMA", "LAURUSLABS": "PHARMA",
    "LUPIN": "PHARMA", "MANKIND": "PHARMA", "SENORES": "PHARMA",
    "SUNPHARMA": "PHARMA", "SYNGENE": "PHARMA", "TORNTPHARM": "PHARMA",
    "ZYDUSLIFE": "PHARMA",

    "APOLLOHOSP": "HEALTHCARE_SERVICES", "ASTERDM": "HEALTHCARE_SERVICES",
    "FORTIS": "HEALTHCARE_SERVICES", "KIMS": "HEALTHCARE_SERVICES",
    "MAXHEALTH": "HEALTHCARE_SERVICES", "MEDANTA": "HEALTHCARE_SERVICES",
    "MEDPLUS": "HEALTHCARE_SERVICES", "NH": "HEALTHCARE_SERVICES",
    "RAINBOW": "HEALTHCARE_SERVICES", "YATHARTH": "HEALTHCARE_SERVICES",

    "BAJAJ-AUTO": "AUTO", "BHARATFORG": "AUTO", "BOSCHLTD": "AUTO",
    "ENDURANCE": "AUTO", "HYUNDAI": "AUTO", "M&M": "AUTO",
    "MARUTI": "AUTO", "MOTHERSON": "AUTO", "SONACOMS": "AUTO",
    "TVSMOTOR": "AUTO", "UNOMINDA": "AUTO", "TMCV": "AUTO", "TMPV": "AUTO",

    "BRITANNIA": "FMCG", "DABUR": "FMCG", "ETERNAL": "FMCG",
    "GODREJCP": "FMCG", "HINDUNILVR": "FMCG", "ITC": "FMCG", "MARICO": "FMCG",
    "NESTLEIND": "FMCG", "PATANJALI": "FMCG", "TATACONSUM": "FMCG",
    "VBL": "FMCG", "CELLO": "FMCG", "THANGAMAYL": "FMCG",

    "HINDALCO": "METALS", "HINDCOPPER": "METALS", "HINDZINC": "METALS",
    "JSL": "METALS", "JSWSTEEL": "METALS", "NATIONALUM": "METALS",
    "SHYAMMETL": "METALS", "TATASTEEL": "METALS", "VEDL": "METALS",
    "GRAVITA": "METALS",

    "ADANIENSOL": "ENERGY", "ADANIGREEN": "ENERGY", "ADANIPOWER": "ENERGY",
    "ATGL": "ENERGY", "BPCL": "ENERGY", "GAIL": "ENERGY", "HINDPETRO": "ENERGY",
    "IOC": "ENERGY", "JSWENERGY": "ENERGY", "KPIGREEN": "ENERGY",
    "NTPC": "ENERGY", "OIL": "ENERGY", "ONGC": "ENERGY", "PETRONET": "ENERGY",
    "POWERGRID": "ENERGY", "POWERINDIA": "ENERGY", "RELIANCE": "ENERGY",
    "SOLARINDS": "ENERGY", "SUZLON": "ENERGY", "TATAPOWER": "ENERGY",
    "TORNTPOWER": "ENERGY", "WAAREEENER": "ENERGY", "OLECTRA": "ENERGY",

    "ACC": "CEMENT", "AMBUJACEM": "CEMENT", "DALBHARAT": "CEMENT",
    "JKCEMENT": "CEMENT", "JSWCEMENT": "CEMENT", "NUVOCO": "CEMENT",
    "RAMCOCEM": "CEMENT", "SHREECEM": "CEMENT", "STARCEMENT": "CEMENT",
    "ULTRACEMCO": "CEMENT",

    "BRIGADE": "REALTY", "DLF": "REALTY", "GODREJPROP": "REALTY",
    "LODHA": "REALTY", "MAHLIFE": "REALTY", "NBCC": "REALTY",
    "OBEROIRLTY": "REALTY", "PHOENIXLTD": "REALTY", "PRESTIGE": "REALTY",
    "SIGNATURE": "REALTY", "ANANTRAJ": "REALTY",

    "AFCONS": "INFRA_CONSTRUCTION", "GVPIL": "INFRA_CONSTRUCTION",
    "GVT&D": "INFRA_CONSTRUCTION", "HGINFRA": "INFRA_CONSTRUCTION",
    "IRCTC": "INFRA_CONSTRUCTION", "KEC": "INFRA_CONSTRUCTION",
    "KPIL": "INFRA_CONSTRUCTION",
    "LT": "INFRA_CONSTRUCTION", "NCC": "INFRA_CONSTRUCTION",
    "RVNL": "INFRA_CONSTRUCTION", "WABAG": "INFRA_CONSTRUCTION",
    "CEIGALL": "INFRA_CONSTRUCTION", "HINDCON": "INFRA_CONSTRUCTION",
    "HINDCOMPOS": "INFRA_CONSTRUCTION", "NCLIND": "INFRA_CONSTRUCTION",

    "AMBER": "CONSUMER_DURABLES", "BLUESTARCO": "CONSUMER_DURABLES",
    "CROMPTON": "CONSUMER_DURABLES", "DIXON": "CONSUMER_DURABLES",
    "HAVELLS": "CONSUMER_DURABLES", "POLYCAB": "CONSUMER_DURABLES",
    "TITAN": "CONSUMER_DURABLES", "VGUARD": "CONSUMER_DURABLES",
    "VOLTAS": "CONSUMER_DURABLES", "WHIRLPOOL": "CONSUMER_DURABLES",
    "KAYNES": "CONSUMER_DURABLES", "NETWEB": "CONSUMER_DURABLES",
    "KEI": "CONSUMER_DURABLES",

    "AARTIIND": "CHEMICALS", "APARINDS": "CHEMICALS", "CLEAN": "CHEMICALS",
    "COROMANDEL": "CHEMICALS", "DEEPAKNTR": "CHEMICALS", "FINEORG": "CHEMICALS",
    "GRASIM": "CHEMICALS", "NAVINFLUOR": "CHEMICALS", "PIDILITIND": "CHEMICALS",
    "PIIND": "CHEMICALS", "SRF": "CHEMICALS", "VINATIORGA": "CHEMICALS",
    "AEGISLOG": "CHEMICALS",

    "BHARTIARTL": "TELECOM", "RAILTEL": "TELECOM",

    "PVRINOX": "MEDIA_ENTERTAINMENT", "NAZARA": "MEDIA_ENTERTAINMENT",

    "DMART": "RETAIL", "TRENT": "RETAIL", "V2RETAIL": "RETAIL",
    "VMART": "RETAIL", "KALYANKJIL": "RETAIL",

    "BLUEDART": "LOGISTICS", "CONCOR": "LOGISTICS", "DELHIVERY": "LOGISTICS",
    "GATEWAY": "LOGISTICS", "GESHIP": "LOGISTICS", "TCI": "LOGISTICS",
    "TCIEXP": "LOGISTICS", "MAHLOG": "LOGISTICS", "LLOYDSME": "LOGISTICS",
    "SWIGGY": "LOGISTICS",

    "ABB": "CAPITAL_GOODS", "BEML": "CAPITAL_GOODS", "CGPOWER": "CAPITAL_GOODS",
    "CUMMINSIND": "CAPITAL_GOODS", "HBLENGINE": "CAPITAL_GOODS",
    "HONDAPOWER": "CAPITAL_GOODS", "SIEMENS": "CAPITAL_GOODS",
    "TARIL": "CAPITAL_GOODS", "APLAPOLLO": "CAPITAL_GOODS",
    "EMIL": "CAPITAL_GOODS", "JLHL": "CAPITAL_GOODS",

    "BEL": "DEFENSE", "GRSE": "DEFENSE", "HAL": "DEFENSE", "MAZDOCK": "DEFENSE",

    "INDHOTEL": "AVIATION_TRAVEL", "INDIGO": "AVIATION_TRAVEL",

    "AFFLE": "DIVERSIFIED", "ADANIENT": "DIVERSIFIED", "ADANIPORTS": "DIVERSIFIED",
    "KAPSTON": "DIVERSIFIED", "LGEINDIA": "DIVERSIFIED",
    "NAUKRI": "DIVERSIFIED", "PNGJL": "DIVERSIFIED", "TVSSCS": "DIVERSIFIED",
    "ARE&M": "DIVERSIFIED", "VTL": "DIVERSIFIED",
}


def sector_for(symbol: str) -> str | None:
    return SECTOR_BY_SYMBOL.get(symbol.strip().upper())
